matrix:
  include:
    - language: python
      python: 2.7
      install:
        - pip install -U platformio
      before_script:
        - pwd
      script:
        - echo 'Trying to build ESP'
        - pwd
        - cd esp
        - pio run

    - language: python
      python: 2.7
      install:
        - pip install -U platformio
      before_script:
        - pwd
      script:
        - echo 'Trying to build SAM'
        - cd sam
        - ./first.sh

    - language: node_js
      node_js:
        - 7
      install:
        - cd mock-api; npm install
        - npm install finalhandler
      before_script:
        - npm run api &
        - npm run web &
        - sleep 2
      script:
        - echo 'Running end to end tests with casperjs'
        - cd mock-api
        - npm -v
        - node -v
        - pwd
        - ls
        - npm run test
